Make `senaite.jsonapi` to be portal-type-naive and allow adapter for create operation (#37)
* Make senaite.jsonapi to be portal_type-naive re creation

* ICreate adapter and documentation

* Delegation of the creation of a portal type via adapter

* Typo

* Changelog

* Remove unncessary code

* Added doctest for searches

* Add doctest for create operation

* Added doctests section in documentation

* Better formatting of doctests

* Fix travis (and version doctest)

* Specified container has priority over config's default

* Bypass permission check on object delete if creation fails

While the problem was that Surname is required, I got this error
when trying to create a Client Contact:

```
File
"/buildout-cache/eggs/plone.jsonapi.core-0.6-py2.7.egg/plone/jsonapi/core/browser/decorators.py",
line 24, in decorator
    return f(*args, **kwargs)
  File
"/buildout-cache/eggs/plone.jsonapi.core-0.6-py2.7.egg/plone/jsonapi/core/browser/api.py",
line 60, in to_json
    return self.dispatch()
  File
"/buildout-cache/eggs/plone.jsonapi.core-0.6-py2.7.egg/plone/jsonapi/core/browser/api.py",
line 54, in dispatch
    return router(self.context, self.request, path)
  File
"/buildout-cache/eggs/plone.jsonapi.core-0.6-py2.7.egg/plone/jsonapi/core/browser/router.py",
line 138, in __call__
    return self.view_functions[endpoint](context, request, **values)
  File
"/zinstance/src/senaite.jsonapi/src/senaite/jsonapi/v1/routes/content.py",
line 89, in action
    items = action_func(portal_type=portal_type, uid=uid)
  File
"/zinstance/src/senaite.jsonapi/src/senaite/jsonapi/api.py",
line 170, in create_items
    obj = create_object(container, portal_type, **record)
  File
"/zinstance/src/senaite.jsonapi/src/senaite/jsonapi/api.py",
line 1408, in create_object
    container.manage_delObjects(obj.id)
  File
"/zinstance/src/senaite.core/bika/lims/content/client.py",
line 267, in manage_delObjects
    "Do not have permissions to remove this object")
Unauthorized: Do not have permissions to remove this object

```

After this change, this is the error I get (correct):

```
APIError: {"Surname": "Surname is required, please correct."}
```

* Additional tests for create operation

* Remove default paths for portal_types (config)

Give responsability to the developer about the container of
the object to be created

* Remove SKIP_CREATION_PORTAL_TYPES_PRODUCTS

* Make tests more robust